import Header from "@/components/Header";
import ProgressBar from "@/components/ProgressBar";
import SectionContainer from "@/components/SectionContainer";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [activeStep, setActiveStep] = useState(0);

  return (
    <>
      <Head>
        <title>Kamea Labs</title>
        <meta name="description" content="Generated by Kamea Labs" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-full">
        <Header />
        <div className="flex gap-2">
          <ProgressBar activeStep={activeStep} setActiveStep={setActiveStep} />
          <SectionContainer activeStep={activeStep} />
        </div>
      </main>
    </>
  );
}
