import Header from "@/components/Header";
import ProgressBar from "@/components/ProgressBar";
import SectionContainer from "@/components/SectionContainer";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [activeStep, setActiveStep] = useState(0);

  return (
    <>
      <Head>
        <title>Kamea Labs</title>
        <meta name="description" content="Generated by Kamea Labs" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen">
        <Header />
        <div className="p-3 text-primary text-center text-sm">
          <div>{text1}</div>
          <div>{text2}</div>
        </div>
        <ProgressBar activeStep={activeStep} setActiveStep={setActiveStep} />
        <SectionContainer
          activeStep={activeStep}
          setActiveStep={setActiveStep}
        />
      </main>
      <div className="sticky bottom-0 p-3 bg-primary text-white text-center text-sm w-full">
        <div>{text1}</div>
        <div>{text2}</div>
      </div>
    </>
  );
}

const text1 =
  " Logion is building the safe digital ownership infrastructure for a Web3 era. You may contribute to this project by pre-buy future logion's token (LGNT).";
const text2 =
  " As it's an early stage project, this opportunity is restricted to investors who understand all related risks - you can lose the entire invested amount - of such investment.";

export const progressSteps = [
  "Presentation from",
  "Synaps KYC",
  "Wallet linking",
  "SAFT Signing",
  "Payment",
];
